# Generated by Django 4.2.4 on 2023-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhaestudo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
