name: CI/CD

on:
  push:
      branches: [main]
jobs:
    CI:
      runs-on: ubuntu-latest

      steps: 
          - name: Checkout
            uses: actions/checkout@v3.6.0 
            
          - name: gcloud Container Registry Docker Login
            uses: elgohr/gcloud-login-action@v2
            with:
               account_key: ${{  secrets.TESTE_DEPLOY }}

